### ISSUE TITLE
Не работает с дробными числами

### ISSUE THREAD

**Issue by Semigradsky** [may42/may42.github.io#10]
В задании было ограничение на целые элементы матриц?

**Comment by may42** [comment]
> Матрицы имею размерность от 2 до 10, максимальное значение в ячейках исходных
> матриц - 10

Действительно, такого ограничения не было, исправлю.
Забыл стереть проверку на дробность: `|| n % 1)`

**Comment by Semigradsky** [comment]
@may42 опять воспроизводится
