### ISSUE TITLE
Обработка исключений

### ISSUE THREAD

**Issue by Semigradsky** [may42/may42.github.io#11]
Сейчас исключения не обрабатываются. Хотя бы в алерте что-то показать (а лучше на sidebar).

Сейчас: нажал "умножить" -> обновилась страница, настройки матриц (размер) сбросились.

**Comment by may42** [comment]
Передавать errorHandler в settings, и сделать так, чтобы он errorMessage выводил на сайдбар?

**Comment by Semigradsky** [comment]
Хз, как сделаешь, я сейчас выступаю в роли пользователя =)

**Comment by may42** [comment]
Я в последней версии сделал пробрасывание ошибок, но я не уверен, что правильно. Там всё жутко сложно.

**Comment by may42** [comment]
Думаю, текущее решение ещё можно доработать, но проблема по большей части решена.
