### ISSUE TITLE
IE 8

### ISSUE THREAD

**Issue by Semigradsky** [may42/may42.github.io#13]
Работает только кнопка "Очистить матрицы". Похоже из-за того, что ты по ошибке подключил вторую версию jQuery

Выглядит сейчас так: 
![image](https://cloud.githubusercontent.com/assets/1198848/13905647/23703764-eed7-11e5-8268-ea46e32f9321.png)

**Comment by may42** [comment]
С помощью чего можно поднять старые версии IE? Эмулятор/виртуальная машина, или что-то типа того? Не имел ещё с этим опыта.

**Comment by Semigradsky** [comment]
Виртуальная машина: https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/
Примерно можно еще посмотреть в любом IE11-, в консоли выбрав режим совместимости с той версией что тебе надо. Но особо получившемуся доверять не нужно.

Еще есть https://www.browserstack.com/, вроде бесплатно какое-то время дают пользоваться, тебе может хватить.

**Comment by Semigradsky** [comment]
В IE8 все-равно не работает, почему-то происходит submit формы.
Reopen! =)

**Comment by Semigradsky** [comment]
В IE10 в режиме совместимости с IE8:
![image](https://cloud.githubusercontent.com/assets/1198848/13978233/a83c94aa-f0e0-11e5-8e0f-14f700a9f27f.png)
В IE8 при использовании defer нарушает порядок выполнения скриптов.

**Comment by Semigradsky** [comment]
После нажатия "Умножить..." генерируется exception с текстом:

> Object doesn't support property or method 'isArray'

**Comment by may42** [comment]
Что лучше, для IE8- использовать полифилл

``` javascript
if (!Array.isArray)
  Array.isArray = function(arg) {
    return Object.prototype.toString.call(arg) === '[object Array]';
  }; // IE 8- polyfill
```

или встроенный в jQuery `$.isArray()` ? Создаст очередную зависимость.

**Comment by Semigradsky** [comment]
Имхо, подключи просто shim:

``` html
<!--[if lt IE 9]>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script>
<![endif]-->
```

**Comment by may42** [comment]
Ох, спасибо, совсем позабыл про ES5-shim
