### ISSUE TITLE
Only digits are allowed in inputs

### ISSUE THREAD

**Issue by may42** [may42/may42.github.io#5]
Нужно ввести запрет на ввод любых нелегальных символов в input-элементы. По условиям задачи, максимальное значение в исходных матрицах равно 10, но ничего не сказано про дробность чисел. Так что, перечень допустимых символов либо `[0-9-]` либо `[0-9.-]`.

**Comment by Semigradsky** [comment]
Как вариант: при потере фокуса форматировать значение инпута.

**Comment by may42** [comment]
Можно ещё поставить слушать события keydown/keypress и просто отменять действие пользователя, если нажата не та клавиша.

**Comment by Semigradsky** [comment]
Главное в этом случае не забыть про
1. клавиши/сочетания типа backspace, tab, shift+tab, del, ctrl+v...
2. вставку значения через ctrl+v, или "правая кнопка мыши"->"вставить"

**Comment by Semigradsky** [comment]
Про "правая кнопка мыши"->"вставить" забыл =)

**Comment by may42** [comment]
Плагин mask не позволяет ничего вставить же.

**Comment by Semigradsky** [comment]
Хм, вчера вставляло, поищу шаги
